ALTER TABLE "branding_settings"
ADD COLUMN IF NOT EXISTS "sidebar_gradient_mid_color" TEXT NOT NULL DEFAULT '#07101F',
ADD COLUMN IF NOT EXISTS "glass_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "glass_opacity" INTEGER NOT NULL DEFAULT 72,
ADD COLUMN IF NOT EXISTS "glass_blur" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN IF NOT EXISTS "glass_saturation" INTEGER NOT NULL DEFAULT 140,
ADD COLUMN IF NOT EXISTS "glass_border_opacity" INTEGER NOT NULL DEFAULT 16;
