import {NextRequest,NextResponse} from 'next/server';
import {auth} from '@/lib/auth';
import {prisma} from '@/lib/prisma';
import {romeAgendaDate} from '@/lib/shift-agenda';
import {resolveShiftResponsible} from '@/lib/shift-responsible-selection-data';
import {emptyShiftAccessDay,hasShiftWriteAccess,normalizeShiftResponsibleAccess,SHIFT_RESPONSIBLE_ACCESS_KEY} from '@/lib/shift-responsible-access';
import {normalizeShiftResponsibleAssignments,WEEKLY_SHIFT_RESPONSIBLES_SETTING_KEY} from '@/lib/weekly-shift-responsibles';
const roles=new Set(['ZERO','SUPER_ADMIN','ADMIN','RESPONSABILE']);
type Saved={note:string;assignee:string;rating:number|null;version:string|null;author:string;taskId?:string;readBy?:string;readAt?:string};
function previous(day:string){const d=new Date(`${day}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10);}
async function load(day:string){const [current,prior,staff]=await Promise.all([prisma.setting.findUnique({where:{key:`shift_tomorrow_${day}`}}),prisma.setting.findUnique({where:{key:`shift_tomorrow_${previous(day)}`}}),prisma.user.findMany({where:{active:true,OR:[{role:{in:['ADMIN','SUPER_ADMIN','RESPONSABILE']}},{location:{name:{contains:'ufficio',mode:'insensitive'}}}]},select:{id:true,name:true},orderBy:{name:'asc'}})]);return {current:current?.value as Saved||{note:'',assignee:'',rating:null,version:null,author:''},prior:prior?.value as Saved|null,priorDay:previous(day),staff};}
export async function GET(req:NextRequest){const s=await auth();if(!s?.user?.id||!roles.has(s.user.role))return NextResponse.json({error:'Non autorizzato'},{status:403});const day=req.nextUrl.searchParams.get('day');if(day!==romeAgendaDate(new Date()))return NextResponse.json({error:'Giorno non valido'},{status:400});try{return NextResponse.json(await load(day),{headers:{'Cache-Control':'private, no-store'}});}catch{return NextResponse.json({error:'Passaggio di consegne non disponibile'},{status:500});}}
export async function PUT(req:NextRequest){const s=await auth();if(!s?.user?.id||!roles.has(s.user.role))return NextResponse.json({error:'Non autorizzato'},{status:403});const b=await req.json().catch(()=>null);if(b?.day!==romeAgendaDate(new Date()))return NextResponse.json({error:'Giorno non valido'},{status:400});
const [access,assignment]=await Promise.all([prisma.setting.findUnique({where:{key:SHIFT_RESPONSIBLE_ACCESS_KEY}}),prisma.setting.findUnique({where:{key:WEEKLY_SHIFT_RESPONSIBLES_SETTING_KEY}})]);if(!hasShiftWriteAccess(normalizeShiftResponsibleAccess(access?.value)[b.day]||emptyShiftAccessDay(),s.user.id,await resolveShiftResponsible(b.day,normalizeShiftResponsibleAssignments(assignment?.value)[b.day])))return NextResponse.json({error:'Serve la presa visione e il permesso di compilare'},{status:403});
try{const data=await load(b.day);const key=`shift_tomorrow_${b.action==='read'?previous(b.day):b.day}`;const setting=await prisma.setting.findUnique({where:{key}});const old=setting?.value as Saved|null;if((old?.version||null)!==b.version)return NextResponse.json({error:'Dati cambiati. Ricarica prima di salvare.'},{status:409});
if(b.action==='read'&&!old?.note)return NextResponse.json({error:'Nessuna nota da leggere'},{status:400});
if(b.action!=='read'&&(typeof b.note!=='string'||b.note.length>5000||typeof b.assignee!=='string'||(b.assignee&&(!b.note.trim()||!data.staff.some(p=>p.id===b.assignee)))||(b.rating!==null&&(!Number.isInteger(b.rating)||b.rating<1||b.rating>5))))return NextResponse.json({error:'Controlla nota, destinatario e valutazione da 1 a 5'},{status:400});
const now=new Date().toISOString();const value:Saved=b.action==='read'?{...old!,version:now,readBy:s.user.name||s.user.id,readAt:now}:{note:b.note.trim(),assignee:b.assignee,rating:b.rating,author:s.user.name||s.user.id,version:now,...(old?.taskId?{taskId:old.taskId}:{})};
await prisma.$transaction(async tx=>{
// Lock the saved version before creating or updating the linked task.
if(setting){const r=await tx.setting.updateMany({where:{key,value:{equals:setting.value!}},data:{value:JSON.parse(JSON.stringify(value))}});if(!r.count)throw new Error('CONFLICT');}else await tx.setting.create({data:{key,value:JSON.parse(JSON.stringify(value))}});
if(b.action!=='read'&&value.assignee){const location=await tx.location.findFirst({where:{name:{contains:'Buenos Aires',mode:'insensitive'}},select:{id:true}});if(!location)throw new Error('Sede non disponibile');const taskData={title:`Consegne del ${b.day}: ${value.note}`.slice(0,120),description:value.note,assignees:{set:[{id:value.assignee}]}};if(old?.taskId)await tx.staffTask.update({where:{id:old.taskId},data:taskData});else{const task=await tx.staffTask.create({data:{title:taskData.title,description:value.note,priority:'MEDIA',category:'Responsabile di turno',location_id:location.id,created_by_id:s.user.id,assignees:{connect:{id:value.assignee}}}});value.taskId=task.id;}
await tx.setting.update({where:{key},data:{value:JSON.parse(JSON.stringify(value))}});
}else if(b.action!=='read'&&old?.taskId){throw new Error('Per una task già creata mantieni un assegnatario. Gestiscila dalla pagina Task.');}
});return NextResponse.json(await load(b.day));}catch(e){return NextResponse.json({error:e instanceof Error&&e.message==='CONFLICT'?'Dati cambiati. Ricarica.':'Salvataggio non riuscito. Se esiste già una task, mantieni un assegnatario.'},{status:409});}}
