import { randomUUID } from "node:crypto";
import assert from "node:assert/strict";
import { NextRequest } from "next/server";
import { GET, POST } from "../app/api/mobile/chat/route";
import { GET as safetyGET, POST as safetyPOST } from "../app/api/mobile/chat/safety/route";
import { POST as filePOST, GET as fileGET } from "../app/api/mobile/chat/files/route";
import { POST as callPOST } from "../app/api/mobile/chat/calls/route";
import { chatDB as db } from "../lib/chat-db";
import { createMobileSession } from "../lib/mobile-auth";
async function main() {
 const url = new URL(process.env.DATABASE_URL!); assert.equal(url.hostname, "127.0.0.1"); assert.equal(url.port, "55439");
 process.env.CHAT_PUSH_ENABLED = "false"; process.env.CALLS_ENABLED = "true";
 process.env.LIVEKIT_URL = "wss://calls.example.invalid"; process.env.LIVEKIT_API_KEY = "test-key"; process.env.LIVEKIT_API_SECRET = "test-secret";
 const stamp = Date.now();
 const users = await Promise.all((["DIPENDENTE", "DIPENDENTE", "ADMIN"] as const).map((role, i) => db.user.create({ data: { name: `Safety ${i}`, email: `safety-${stamp}-${i}@example.invalid`, password_hash: "not-a-login", role } })));
 const [a,b,admin] = users; const [ta,tb,tm] = await Promise.all(users.map(async u => (await createMobileSession(u.id)).token));
 const request = (token: string, path: string, data?: object) => new NextRequest("http://localhost"+path, { method: data ? "POST" : "GET", headers: { authorization: `Bearer ${token}` }, ...(data ? { body: JSON.stringify(data) } : {}) });
 const post = (t: string, d: object) => POST(request(t,"/api/mobile/chat",d));
 const safety = (t: string, d: object) => safetyPOST(request(t,"/api/mobile/chat/safety",d));
 const roomId = (await (await post(ta,{action:"create", kind:"direct", members:[b.id]})).json()).id;
 const msg = (await (await post(tb,{action:"send",roomId,body:"Segnalabile",clientId:"safety-message"})).json()).message;
 assert.equal((await post(tb,{action:"send",roomId,body:"ti uccido",clientId:"safety-filter"})).status,400);
 assert.equal((await safety(tm,{action:"report",messageId:msg.id,reason:"No accesso"})).status,404);
 assert.equal((await safety(ta,{action:"report",messageId:msg.id,reason:"Molestie"})).status,200);
 assert.equal((await safety(ta,{action:"report",messageId:msg.id,reason:"Duplicate"})).status,200);
 assert.equal((await safetyGET(request(ta,"/api/mobile/chat/safety?reports=1"))).status,403);
 const reports = (await (await safetyGET(request(tm,"/api/mobile/chat/safety?reports=1"))).json()).reports;
 const report = reports.find((r: {messageId:string})=>r.messageId===msg.id); assert.ok(report); assert.equal(report.body,"Segnalabile");
 assert.equal((await GET(request(tm,`/api/mobile/chat?roomId=${roomId}`))).status,404);
 const upload = await filePOST(request(tb,"/api/mobile/chat/files",{roomId, clientId:"safety-file",filename:"test.txt",data:Buffer.from("documento").toString("base64")}));
 assert.equal(upload.status,200); const uploadId = (await upload.json()).id; const attachment = (await db.chatAttachment.findUniqueOrThrow({where:{messageId:uploadId}}));
 assert.equal((await safety(ta,{action:"report",messageId:uploadId,reason:"Allegato inappropriato"})).status,200);
 const fileReports = (await (await safetyGET(request(tm,"/api/mobile/chat/safety?reports=1"))).json()).reports;
 const fileReport = fileReports.find((r: {messageId:string})=>r.messageId===uploadId);
 assert.equal((await fileGET(request(tm,`/api/mobile/chat/files?id=${attachment.id}`))).status,404);
 assert.equal((await fileGET(request(ta,`/api/mobile/chat/files?id=${attachment.id}&reportId=${fileReport.id}`))).status,403);
 assert.equal((await fileGET(request(tm,`/api/mobile/chat/files?id=${attachment.id}&reportId=${report.id}`))).status,404);
 assert.equal((await fileGET(request(tm,`/api/mobile/chat/files?id=${attachment.id}&reportId=${fileReport.id}`))).status,200);
 const groupId = (await (await post(tm,{action:"create",kind:"group",title:"Safety group",members:[a.id,b.id]})).json()).id;
 await post(tb,{action:"send",roomId:groupId,body:"Gruppo",clientId:"group-blocked"});
 assert.equal((await safety(ta,{action:"block",targetId:b.id})).status,200);
 const groupMessages = await (await GET(request(ta,`/api/mobile/chat?roomId=${groupId}`))).json();
 assert.equal(groupMessages.messages.length,0);
 assert.equal((await callPOST(request(tb,"/api/mobile/chat/calls",{action:"start",roomId,id:randomUUID()}))).status,403);
 assert.equal((await post(tb,{action:"send",roomId,body:"No",clientId:"blocked"})).status,403);
 assert.equal((await post(ta,{action:"send",roomId,body:"No",clientId:"blocked2"})).status,403);
 assert.equal((await filePOST(request(tb,"/api/mobile/chat/files",{roomId,clientId:"blocked-file",filename:"a.txt",data:Buffer.from("no").toString("base64")}))).status,403);
 assert.equal((await fileGET(request(ta,`/api/mobile/chat/files?id=${attachment.id}`))).status,404);
 const hidden = await (await GET(request(ta,`/api/mobile/chat?roomId=${roomId}`))).json(); assert.equal(hidden.messages.length,0); assert.ok(hidden.blockedUserIds.includes(b.id));
 assert.equal((await safety(tb,{action:"unblock",targetId:a.id})).status,200);
 assert.equal((await post(tb,{action:"send",roomId,body:"No",clientId:"still-blocked"})).status,403);
 assert.equal((await safety(ta,{action:"unblock",targetId:b.id})).status,200);
 assert.equal((await post(tb,{action:"send",roomId,body:"Si",clientId:"unblocked"})).status,200);
 assert.equal((await safety(ta,{action:"resolve",reportId:report.id,resolution:"remove"})).status,403);
 assert.equal((await safety(tm,{action:"resolve",reportId:report.id,resolution:"suspend"})).status,200);
 assert.equal((await GET(request(tb,"/api/mobile/chat"))).status,403);
 assert.equal((await safety(ta,{action:"restore",targetId:b.id})).status,403);
 assert.equal((await safety(tm,{action:"restore",targetId:b.id})).status,200);
 assert.equal((await GET(request(tb,"/api/mobile/chat"))).status,200);
 assert.ok((await db.chatMessage.findUnique({where:{id:msg.id}}))?.deletedAt);
 console.log("Safety integration passed: isolation, screening, reporting, idempotency, bidirectional blocks, attachments, moderator authorization, suspension and restoration");
}
main().catch(e=>{ console.error(e);process.exitCode=1; }).finally(()=>db.$disconnect());
