import assert from "node:assert/strict";
import { chatPushPayload } from "../lib/chat-push";
const message = { id: "m1", roomId: "r1", body: "Ciao!", user: { id: "u1", name: "Aurora", photo_url: "/api/drive-image?id=photo" }, room: { kind: "direct", title: "Team" }, attachment: null };
const direct = chatPushPayload(message, 2);
assert.equal(direct.aps.alert.title, "Aurora");
assert.equal(direct.aps.alert.body, "Ciao!");
assert.equal(direct.senderPhoto, message.user.photo_url);
assert.equal(direct.aps["mutable-content"], 1);
assert.equal(direct.roomId, "r1");
assert.equal(direct.aps.badge, 2);
assert.equal(direct.isGroup, false);
assert.equal(direct.aps.alert.subtitle, undefined);
const photo = chatPushPayload({ ...message, room: { kind: "group", title: "Salone" }, attachment: { mediaType: "image/png", filename: "test.png" } }, 1);
assert.equal(photo.aps.alert.body, "📷 Foto");
assert.equal(photo.aps.alert.subtitle, "Salone");
assert.equal(photo.isGroup, true);
const empty = chatPushPayload({ ...message, body: "   ", user: { ...message.user, photo_url: null } }, 0);
assert.equal(empty.aps.alert.body, "Nuovo messaggio");
const huge = chatPushPayload({ ...message, body: "🙂".repeat(5000), user: { ...message.user, photo_url: "x".repeat(9000) } }, 9);
assert.equal(huge.senderPhoto, null);
assert.ok(Buffer.byteLength(JSON.stringify(huge)) < 4096);
console.log("Chat push payload checks passed");
