import assert from "node:assert/strict";
import { NextRequest } from "next/server";
import { POST as pushPOST } from "../app/api/mobile/chat/push/route";
import { GET as fileGET, POST as filePOST } from "../app/api/mobile/chat/files/route";
import { GET, POST } from "../app/api/mobile/chat/route";
import { chatDB as db } from "../lib/chat-db";
import { prisma } from "../lib/prisma";
import { createMobileSession } from "../lib/mobile-auth";

async function main() {
  const url = new URL(process.env.DATABASE_URL!);
  assert.equal(url.hostname, "127.0.0.1"); assert.equal(url.port, "55439");
  assert.equal(process.env.INTERNAL_CHAT_ENABLED, "true");
  const run = Date.now();
  const a = await db.user.create({ data: { name: "Test A", email: `chat-a-${run}@example.invalid`, password_hash: "not-a-login", role: "DIPENDENTE" } });
  const b = await db.user.create({ data: { name: "Test B", email: `chat-b-${run}@example.invalid`, password_hash: "not-a-login", role: "DIPENDENTE" } });
  const admin = await db.user.create({ data: { name: "Test Admin", email: `chat-admin-${run}@example.invalid`, password_hash: "not-a-login", role: "ADMIN" } });
  const tokenA = (await createMobileSession(a.id)).token;
  const tokenB = (await createMobileSession(b.id)).token;
  const tokenAdmin = (await createMobileSession(admin.id)).token;
  async function get(token: string, query = "") { return GET(new NextRequest("http://localhost/api/mobile/chat" + query, { headers: { authorization: `Bearer ${token}` } })); }
  async function post(token: string, data: object) { return POST(new NextRequest("http://localhost/api/mobile/chat", { method: "POST", headers: { authorization: `Bearer ${token}` }, body: JSON.stringify(data) })); }
  assert.equal((await get("invalid")).status, 401);
  process.env.CHAT_PUSH_ENABLED = "false";
  assert.equal((await pushPOST(new NextRequest("http://localhost/api/mobile/chat/push", { method: "POST", headers: { authorization: `Bearer ${tokenA}` }, body: "{}" }))).status, 503);
  const created = await post(tokenA, { action: "create", kind: "direct", members: [b.id] });
  assert.equal(created.status, 200); const roomId = (await created.json()).id;
  const duplicateRoom = await post(tokenB, { action: "create", kind: "direct", members: [a.id] });
  assert.equal((await duplicateRoom.json()).id, roomId);
  assert.equal((await get(tokenAdmin, `?roomId=${roomId}`)).status, 404);
  assert.deepEqual((await (await get(tokenAdmin)).json()).rooms, []);
  const message = { action: "send", roomId, body: "Messaggio di prova", clientId: "retry-test" };
  const sent = await post(tokenA, message); assert.equal(sent.status, 200);
  const messageId = (await sent.json()).message.id;
  assert.equal((await (await post(tokenA, message)).json()).message.id, messageId);
  const inbox = await (await get(tokenB)).json(); assert.equal(inbox.rooms[0].unread, 1);
  assert.equal((await post(tokenAdmin, { ...message, clientId: "intruder" })).status, 404);
  assert.equal((await post(tokenB, { action: "edit", roomId, messageId, body: "Alterato" })).status, 403);
  assert.equal((await post(tokenA, { action: "edit", roomId, messageId, body: "Corretto" })).status, 200);
  assert.equal((await (await get(tokenB, `?roomId=${roomId}`)).json()).messages[0].body, "Corretto");
  assert.equal((await post(tokenB, { action: "read", roomId, messageId })).status, 200);
  assert.equal((await (await get(tokenB)).json()).rooms[0].unread, 0);
  assert.equal((await post(tokenA, { action: "create", kind: "channel", title: "Riservato", members: [b.id] })).status, 403);
  const group = await post(tokenAdmin, { action: "create", kind: "channel", title: "Riservato", members: [b.id] });
  assert.equal(group.status, 200); const channelId = (await group.json()).id;
  assert.equal((await get(tokenA, `?roomId=${channelId}`)).status, 404);
  assert.equal((await post(tokenB, { action: "archive", roomId: channelId })).status, 403);
  assert.equal((await post(tokenAdmin, { action: "archive", roomId: channelId })).status, 200);
  assert.equal((await post(tokenB, { action: "send", roomId: channelId, body: "No", clientId: "archived" })).status, 409);
  assert.equal((await post(tokenA, { ...message, body: " ", clientId: "empty" })).status, 400);
  assert.equal((await post(tokenA, { ...message, body: "a".repeat(4001), clientId: "long" })).status, 400);
  assert.equal((await post(tokenA, { action: "delete", roomId, messageId })).status, 200);
  assert.equal((await (await get(tokenB, `?roomId=${roomId}`)).json()).messages[0].body, "Messaggio eliminato");
  const upload = { roomId, clientId: "attachment-retry", filename: "prova.txt", data: Buffer.from("Documento di prova riservato").toString("base64") };
  const fileRequest = (token: string, body: object) => new NextRequest("http://localhost/api/mobile/chat/files", { method: "POST", headers: { authorization: `Bearer ${token}` }, body: JSON.stringify(body) });
  const download = (token: string, id: string) => fileGET(new NextRequest(`http://localhost/api/mobile/chat/files?id=${id}`, { headers: { authorization: `Bearer ${token}` } }));
  assert.equal((await filePOST(fileRequest(tokenAdmin, upload))).status, 404);
  assert.equal((await filePOST(fileRequest(tokenA, { ...upload, filename: "fake.pdf" }))).status, 400);
  const uploaded = await filePOST(fileRequest(tokenA, upload)); assert.equal(uploaded.status, 200);
  const uploadedId = (await uploaded.json()).id;
  assert.equal((await (await filePOST(fileRequest(tokenA, upload))).json()).id, uploadedId);
  const attached = await db.chatAttachment.findUniqueOrThrow({ where: { messageId: uploadedId } });
  assert.equal((await download(tokenAdmin, attached.id)).status, 404);
  assert.equal(await (await download(tokenB, attached.id)).text(), "Documento di prova riservato");
  const metadata = (await (await get(tokenB, `?roomId=${roomId}`)).json()).messages.find((m: { id: string }) => m.id === uploadedId).attachment;
  assert.equal(metadata.filename, "prova.txt"); assert.equal(metadata.data, undefined);
  assert.equal((await filePOST(fileRequest(tokenA, { ...upload, clientId: "too-big", data: Buffer.alloc(5 * 1024 * 1024 + 1, 65).toString("base64") }))).status, 413);
  assert.equal((await post(tokenA, { action: "delete", roomId, messageId: uploadedId })).status, 200);
  assert.equal((await download(tokenB, attached.id)).status, 404);
  await db.user.update({ where: { id: b.id }, data: { active: false } });
  assert.equal((await get(tokenB, `?roomId=${roomId}`)).status, 401);
  await db.user.update({ where: { id: b.id }, data: { active: true, employee_status: "Ex dipendente" } });
  assert.equal((await get(tokenB)).status, 401);
  // A fresh DB client must see persisted rows (no in-memory chat store).
  await db.$disconnect();
  assert.equal(await db.chatMessage.count({ where: { roomId } }), 2);
  const stamp = new Date();
  await db.chatMessage.createMany({ data: Array.from({ length: 55 }, (_, i) => ({ id: `page-${run}-${String(i).padStart(3, "0")}`, roomId, userId: a.id, clientId: `page-${run}-${i}`, body: "Pagination test", createdAt: stamp })) });
  const firstPage = await (await get(tokenA, `?roomId=${roomId}`)).json();
  assert.equal(firstPage.messages.length, 50); assert.equal(firstPage.hasMore, true);
  const secondPage = await (await get(tokenA, `?roomId=${roomId}&before=${firstPage.messages[0].id}`)).json();
  assert.equal(new Set([...firstPage.messages, ...secondPage.messages].map(m => m.id)).size, 57);
  process.env.INTERNAL_CHAT_ENABLED = "false";
  assert.equal((await get(tokenA)).status, 503);
  process.env.INTERNAL_CHAT_ENABLED = "true";
  console.log("PASS: chat lifecycle, 3 accounts, private channel access, admin isolation, retry deduplication, unread/read, edit/delete ownership, archive, invalid input, suspended/former employee, persistence, private attachments, file validation and size limits.");
}
main().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { await db.$disconnect(); await prisma.$disconnect(); });
