'use client';

import {useEffect, useState} from 'react';
import type {DirectionBonusData} from '@/lib/direction-bonus-data';
import {eventFingerprint, type BonusRules} from '@/lib/direction-bonus';
import './direction-bonus-dashboard.css';

const euro=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const labels:Record<string,string>={ontime:'Chiuso in orario',late:'Chiuso in ritardo',incomplete:'Incompleto',missing:'Mancante',progress:'In compilazione',future:'Da venire',notplanned:'Non programmato'};
const sections:Record<string,string>={agenda:'Agenda',team:'Team',hair:'Capelli',products:'Prodotti',cash:'Cassa',tomorrow:'Domani',client_cases:'Clienti'};
const ruleNames:Partial<Record<keyof BonusRules,string>>={point:'Euro per punto media',days:'Divisore mensile',lauraDays:'Divisore Laura',shared:'Peso scheda condivisa',entryGrace:'Tolleranza ingresso (min)',late:'Ritardo / pausa (€)',positive:'Recensione positiva (€)',negative:'Recensione negativa (€)',rework:'Lavoro imputabile (€)',repair:'Sistemazione collega (€)',open:'Scheda aperta (€)'};
const fieldNames:Record<string,string>={notes:'Risposte',decisions:'Verifiche',choice:'Esito',note:'Nota',presentation:'Presentabilità',exceptions:'Eccezioni',userId:'Persona',reason:'Motivo',closed:'Chiusura cassa effettuata',discrepancy:'Discrepanze',amount:'Importo',kind:'Tipo',explanation:'Spiegazione',lowStock:'Scorta bassa',rows:'Voci',needed:'Prodotti necessari',quantity:'Quantità',name:'Nome',present:'Quantità presente',order:'Da ordinare',outcomes:'Esiti appuntamenti',waits:'Attese',minutes:'Minuti',solution:'Soluzione',description:'Descrizione',authorizedBy:'Autorizzato da',performedBy:'Svolto da',rating:'Valutazione',assigneeId:'Assegnato a',confirmedBy:'Confermato da',confirmedAt:'Confermato il'};
function SourceValue({value,people}:{value:unknown;people:{id:string;name:string}[]}) {
 if(value==null||value==='')return <span>—</span>;
 if(typeof value==='boolean')return <span>{value?'Sì':'No'}</span>;
 if(typeof value!=='object'){const raw=String(value);const person=people.find(p=>p.id===raw);return <span>{person?.name||({all:'Tutto regolare',exceptions:'Eccezioni segnalate',MISSING:'Manca',EXTRA:'In più'}[raw]||raw)}</span>;}
 return <dl className="direction-source">{Object.entries(value).filter(([key])=>!['revision','fingerprint','version','savedBy','productId','bookingId','id'].includes(key)).map(([key,v])=><div key={key}><dt>{fieldNames[key]||people.find(p=>key.startsWith(p.id))?.name||(/^\d+$/.test(key)?`Voce ${Number(key)+1}`:key.replaceAll('_',' '))}</dt><dd><SourceValue value={v} people={people}/></dd></div>)}</dl>;
}
export function DirectionBonusDashboard({initialMonth}:{initialMonth:string}){
 const [review,setReview]=useState({userId:'',day:'',reference:''});const [month,setMonth]=useState(initialMonth);const [data,setData]=useState<DirectionBonusData|null>(null);const [rules,setRules]=useState<BonusRules|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [tab,setTab]=useState(0);const [person,setPerson]=useState('');const [day,setDay]=useState('');const [reason,setReason]=useState<Record<string,string>>({});
 useEffect(()=>{const abort=new AbortController();setData(null);setError('');fetch(`/api/direction-bonus?month=${month}`,{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setRules(d.rules);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[month]);
 async function act(action:string,extra:Record<string,unknown>={}){if(!data)return;setBusy(true);setError('');try{const r=await fetch('/api/direction-bonus',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month,revision:data.state.revision,action,...extra})});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setRules(d.rules);}catch(e){setError(e instanceof Error?e.message:'Salvataggio non riuscito');}finally{setBusy(false);}}
 async function refresh(){setBusy(true);try{const r=await fetch(`/api/direction-bonus?month=${month}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setRules(d.rules);setError('');}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function pdf(id:string){if(!data)return;try{const {directionPdf}=await import('@/lib/direction-bonus-export');directionPdf(data,id).save(`anteprima-bonus-${month}-${id}.pdf`);}catch{setError('Impossibile generare il PDF.');}}
 async function csv(){if(!data)return;const {csvCell}=await import('@/lib/direction-bonus-export');const rows=[['Persona','Data','Fonte','Evento','Quantità','Importo provvisorio','Decisione','Motivo'],...data.events.map(e=>[data.people.find(p=>p.id===e.userId)?.name,e.day,e.source,e.label,e.units,e.amount,data.state.decisions[e.id]?.choice||'',data.state.decisions[e.id]?.reason||''])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`audit-provvisorio-${month}.csv`;a.click();URL.revokeObjectURL(url);}
 const currentDay=data?.calendar.find(c=>c.day===day);const pending=data?.rows.reduce((n,r)=>n+r.pending,0)||0;
 return <section className="direction-dashboard">
  <header className="direction-heading"><div><span className="direction-eyebrow">DIREZIONE · DATI, CONTROLLI E BONUS</span><h1>Pannello direzione</h1><p>Dal verbale giornaliero al riepilogo mensile. Accesso riservato alla direzione e agli admin.</p></div><label>Mese di competenza<input aria-label="Mese di competenza" type="month" min="2026-09" max={initialMonth} value={month} onChange={e=>{setMonth(e.target.value);setDay('');setPerson('');}}/></label></header>
  {error&&<p className="direction-error" role="alert">{error}</p>}
  {!data?<p aria-live="polite">{error?'Dati non caricati.':'Caricamento verbali, turnistica e timbrature…'}</p>:<>
  <div className="direction-summary"><div><small>Verbali chiusi</small><strong>{data.calendar.filter(c=>['ontime','late'].includes(c.state)).length} / {data.calendar.filter(c=>c.state!=='future'&&c.state!=='notplanned').length}</strong></div><div><small>Voci da verificare</small><strong>{data.issues.length}</strong></div><div><small>Decisioni richieste</small><strong>{pending}</strong></div><div><small>Persone nel bonus</small><strong>{data.rows.length}</strong></div></div>
  <div className="direction-notice"><strong>Anteprima {data.partial?'del mese in corso':'da verificare'}</strong><span>I totali non sono approvati. Le fonti mancanti sono elencate nella chiusura dati.</span><button disabled={busy} onClick={refresh}>Aggiorna dati</button></div>
  <nav className="direction-steps" aria-label="Fasi del mese">{['Chiusura dati','Calcolo bonus','Decisioni','Approvazione','Esporta'].map((t,i)=><button key={t} aria-current={tab===i?'step':undefined} onClick={()=>setTab(i)}><b>{i+1}</b>{t}</button>)}</nav>
  {tab===0&&<>
   <section className="direction-panel" id="verbali"><h2>Verbali del mese</h2><p>Verde: chiusura entro le 19:30 · ambra: incompleto o in ritardo · rosa: mancante.</p><div className="direction-weekdays">{['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map(d=><span key={d}>{d}</span>)}</div><div className="direction-days">{Array.from({length:(new Date(`${month}-01T12:00:00Z`).getUTCDay()+6)%7},(_,i)=><div aria-hidden="true" className="direction-day-offset" key={`offset-${i}`}/>)}{data.calendar.map(c=><button key={c.day} className={`direction-day ${c.state}`} disabled={c.state==='future'} onClick={()=>setDay(day===c.day?'':c.day)} aria-expanded={day===c.day}><strong>{c.day.slice(8)}</strong><span>{c.responsible}</span><small>{labels[c.state]}</small></button>)}</div>{currentDay&&<div className="direction-detail"><h3>Verbale del {currentDay.day} · {currentDay.responsible}</h3><p>{labels[currentDay.state]}{currentDay.closedAt?` · ${new Date(currentDay.closedAt).toLocaleString('it-IT')}`:''}</p>{Object.entries(currentDay.sections).map(([k,v])=><details key={k}><summary>{sections[k]} · {v?'risposte salvate':'nessuna risposta'}</summary><SourceValue value={v} people={data.people}/></details>)}</div>}</section>
   <section className="direction-panel" id="recensioni-positive"><h2>Recensioni positive nominative</h2><p>Collega ogni recensione alla persona citata e alla data. Il riferimento serve per ritrovarla e verificarla.</p><div className="direction-rules"><label>Persona<select value={review.userId} onChange={e=>setReview({...review,userId:e.target.value})}><option value="">Seleziona…</option>{data.rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Data recensione<input type="date" min={`${month}-01`} max={data.today.slice(0,7)===month?data.today:`${month}-${new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()}`} value={review.day} onChange={e=>setReview({...review,day:e.target.value})}/></label><label>Link o riferimento<input value={review.reference} onChange={e=>setReview({...review,reference:e.target.value})}/></label></div><button disabled={busy||!review.userId||!review.day||!review.reference.trim()} onClick={()=>act('positive_review',review)}>Collega recensione</button>{(data.state.positiveReviews||[]).map(r=><p key={r.id}>{r.day} · {data.people.find(p=>p.id===r.userId)?.name} · {r.reference}</p>)}<p>Quando hai controllato tutte le recensioni del mese, conferma anche se non ne risultano di positive nominative.</p><button disabled={busy||data.state.positiveReviewed} onClick={()=>act('reviews_checked')}>{data.state.positiveReviewed?'Verifica registrata':'Conferma verifica recensioni positive'}</button></section>
   <section className="direction-panel"><h2>Prima del calcolo · {data.issues.length} voci aperte</h2>{data.issues.length===0?<p className="direction-good">Nessuna anomalia bloccante rilevata.</p>:data.issues.map(i=><div className="direction-issue" key={i.id}><div><small>{i.kind} · {i.day}</small><p>{i.label}</p></div>{i.acknowledge?<button disabled={busy} onClick={()=>act('seen',{id:i.id})}>Ho preso visione</button>:<a href={i.href} onClick={i.href==='#regole'?()=>setTab(1):undefined}>Controlla →</a>}</div>)}<p>La presa visione di un verbale mancante non lo rende completo.</p><button className="direction-primary" onClick={()=>setTab(1)}>Vai al calcolo →</button></section>
  </>}
  {tab===1&&<>
   <section className="direction-panel"><h2>Bonus mensile · anteprima</h2><p>Schede confermate + quota delle condivise, divise per i giorni previsti dalle regole. Le schede aperte richiedono una decisione.</p><div className="direction-table-wrap"><table><thead><tr>{['Persona','Schede pesate','Media','Base','Ritardi','Recensioni +','Recensioni −','Imputabili','Sistemazioni','Schede aperte','Totale provvisorio'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><th><button onClick={()=>setPerson(person===r.id?'':r.id)}>{r.name} ↗</button></th><td>{r.cards}</td><td>{r.average.toFixed(1)}</td><td>{euro(r.base)}</td>{(['late','positive','negative','rework','repair','open'] as const).map(k=><td key={k} className={r.amounts[k]<0?'direction-negative':''}>{euro(r.amounts[k])}</td>)}<td><b>{euro(r.total)}</b></td></tr>)}</tbody></table></div><button className="direction-primary" disabled={busy||data.issues.length>0} onClick={()=>act('calculate')}>Calcola dalle fonti aggiornate</button>{data.issues.length>0&&<p>Risolvi le {data.issues.length} voci nella chiusura dati per registrare il calcolo.</p>}</section>
   {person&&<section className="direction-panel"><h2>{data.people.find(p=>p.id===person)?.name} · dettaglio</h2><h3>Timbrature e turni</h3><div className="direction-table-wrap"><table><thead><tr><th>Giorno</th><th>Turno</th><th>Entrata</th><th>Pause</th><th>Uscita</th></tr></thead><tbody>{data.daily.filter(d=>d.userId===person).map(d=><tr key={d.day}><td>{d.day}</td><td>{d.start?`${d.start}–${d.end}`:d.shift}</td><td>{d.entry||'—'}</td><td>{d.pauses||'—'}</td><td>{d.exit||'—'}</td></tr>)}</tbody></table></div><h3>Eventi del bonus</h3>{data.events.filter(e=>e.userId===person).map(e=><p key={e.id}>{e.day} · {e.label} · <b>{e.kind==='card'?`${e.units} schede`:euro(e.amount)}</b></p>)}<button onClick={()=>pdf(person)}>Scarica anteprima PDF personale</button></section>}
   {rules&&<details className="direction-panel" id="regole"><summary>Regole e partecipanti · valide da {rules.effectiveMonth}</summary><div className="direction-rules">{Object.entries(ruleNames).map(([k,label])=><label key={k}>{label}<input type="number" step="any" value={Number(rules[k as keyof BonusRules])} onChange={e=>setRules({...rules,[k]:Number(e.target.value)})}/></label>)}<label>Importi<select value={rules.taxLabel} onChange={e=>setRules({...rules,taxLabel:e.target.value as BonusRules['taxLabel']})}><option value="">Da confermare</option><option value="NETTO">Netti</option><option value="LORDO">Lordi</option></select></label><label>Totale negativo<select value={rules.negativeFloor===null?'':String(rules.negativeFloor)} onChange={e=>setRules({...rules,negativeFloor:e.target.value===''?null:e.target.value==='true'})}><option value="">Da confermare</option><option value="true">Ferma a zero</option><option value="false">Mantieni negativo</option></select></label></div><h3>Persone incluse</h3><div className="direction-participants">{data.people.filter(p=>p.active||rules.participants.includes(p.id)).map(p=><label key={p.id}><input type="checkbox" checked={rules.participants.includes(p.id)} onChange={e=>setRules({...rules,participants:e.target.checked?[...rules.participants,p.id]:rules.participants.filter(id=>id!==p.id)})}/>{p.name}</label>)}</div><p>Quota gestione disattivata: i sette indicatori devono essere collegati prima di applicarla.</p><button className="direction-primary" disabled={busy} onClick={()=>act('rules',{rules:{...rules,effectiveMonth:month}})}>Salva regole da questo mese</button></details>}
  </>}
  {tab===2&&<section className="direction-panel"><h2>Decisioni della direzione</h2><p>Ogni modifica conserva evento originale, motivo, autore e data.</p>{!data.state.calculatedAt&&<p className="direction-notice">Completa prima la chiusura dati e registra il calcolo per salvare le decisioni.</p>}{data.events.filter(e=>e.needsDecision||e.kind!=='card').map(e=>{const decision=data.state.decisions[e.id];const valid=decision?.fingerprint===eventFingerprint(e);return <article className="direction-decision" key={e.id}><small>{e.day} · {data.people.find(p=>p.id===e.userId)?.name} · {e.source}</small><h3 style={{textDecoration:valid&&decision.choice==='CANCEL'?'line-through':undefined}}>{e.label}</h3><p>{e.note} {e.kind==='card'?`${e.units} schede`:euro(e.amount)}</p>{valid&&<p>Decisione: {decision.choice==='COUNT'?'Conta':'Non conta'} · {decision.reason} · {decision.actor}</p>}<label>Motivo della decisione<textarea maxLength={2000} value={reason[e.id]||''} onChange={v=>setReason({...reason,[e.id]:v.target.value})}/></label><div className="direction-actions"><button disabled={busy||!data.state.calculatedAt||data.issues.length>0||!reason[e.id]?.trim()} onClick={()=>act('decision',{id:e.id,choice:'COUNT',reason:reason[e.id]})}>Conta</button><button disabled={busy||!data.state.calculatedAt||data.issues.length>0||!reason[e.id]?.trim()} onClick={()=>act('decision',{id:e.id,choice:'CANCEL',reason:reason[e.id]})}>Non conta</button></div></article>;})}</section>}
  {tab===3&&<section className="direction-panel"><h2>Approvazione del mese</h2><p>Il mese non è ancora approvabile.</p><ul><li>{data.issues.length} voci aperte nelle fonti.</li><li>{pending} decisioni da registrare.</li>{!data.rules.taxLabel&&<li>Confermare se gli importi sono netti o lordi.</li>}{data.rules.negativeFloor===null&&<li>Confermare il trattamento dei totali negativi.</li>}<li>Verificare settembre contro il foglio e i PDF originali.</li><li>Completare il blocco delle fonti dopo l’approvazione e la riapertura con motivazione.</li></ul><button disabled>Approva e blocca il mese</button><h3>Registro delle operazioni</h3>{data.state.audit.length===0?<p>Nessuna operazione registrata.</p>:data.state.audit.slice().reverse().map(a=><p key={a.id}>{new Date(a.at).toLocaleString('it-IT')} · <b>{a.actor}</b> · {a.reason}</p>)}</section>}
  {tab===4&&<section className="direction-panel"><h2>Documenti e verifiche</h2><p>Le esportazioni attuali sono anteprime per la direzione. L’invio al personale e il file paghe saranno disponibili dopo l’approvazione.</p><button onClick={csv}>Scarica audit eventi CSV</button><div className="direction-export">{data.rows.map(r=><div key={r.id}><span>{r.name}</span><button onClick={()=>pdf(r.id)}>Anteprima PDF</button></div>)}</div><button disabled>Esporta paghe definitive</button></section>}
  </>}
 </section>;
}
