'use client';
import { useEffect, useState } from 'react';
import { BONUS_EVENT_LABELS, BONUS_LEVELS, BONUS_START_DATE, BONUS_START_MONTH, canRegisterBonus, type BonusAccount, type BonusActor, type BonusEventType } from '@/lib/monthly-bonus';
import type { BonusAudit, BonusConfig, BonusPerson } from '@/lib/monthly-bonus-state';

type Row=BonusPerson & {config:BonusConfig|null;account:BonusAccount|null;balance:{base:number;cap:number;bonus:number;malus:number;points:number;euros?:number}|null};
type Data={showValue:boolean;valueVisible:boolean;month:string;today:string;actor:BonusActor;admin:boolean;revision:number;people:Row[];assignments:BonusPerson[];audit:BonusAudit[]};
const money=(n:number)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);
const num=(n:number)=>new Intl.NumberFormat('it-IT').format(n);
const box='rounded-2xl border border-pink-100 bg-white p-5 text-neutral-900 shadow-sm';
const input='min-h-11 w-full rounded-xl border border-neutral-200 bg-white p-3 text-sm text-neutral-900';
const button='min-h-11 rounded-xl bg-pink-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-40';
async function post(body:unknown){const response=await fetch('/api/monthly-bonus',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const json=await response.json();if(!response.ok)throw new Error(json.error??'Salvataggio non riuscito.');return json;}
export function MonthlyBonusClient({initialMonth}:{initialMonth:string}){
 const [month,setMonth]=useState(initialMonth),[data,setData]=useState<Data|null>(null),[tab,setTab]=useState('personal'),[selected,setSelected]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');fetch(`/api/monthly-bonus?month=${month}`,{signal:abort.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setSelected(old=>d.people.some((p:Row)=>p.id===old)?old:d.actor.id);}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[month,refresh]);
 const reload=(message:string)=>{setNotice(message);setRefresh(r=>r+1)};
 const p=data?.people.find(p=>p.id===selected)??data?.people[0];
 const manageable=data?.people.filter(p=>p.config&&Object.keys(BONUS_EVENT_LABELS).some(t=>canRegisterBonus(data.actor,p.config!,t as BonusEventType)))??[];
 return <div className="mx-auto max-w-6xl space-y-5 px-3 py-6 sm:px-6">
  <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-pink-600">Paradise · Centro Punti</p><h1 className="mt-2 text-3xl font-bold">Il tuo mese, i tuoi punti</h1><p className="mt-2 text-sm text-neutral-500">{data?.showValue?'1 punto = 5 € · ':''}Conti separati per mese · Attivo dal 28 settembre 2026</p></div><label className="text-xs">Mese<input className={input} type="month" min={BONUS_START_MONTH} max={initialMonth} value={month} onChange={e=>{if(e.target.value){setData(null);setMonth(e.target.value)}}}/></label></div>
  {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-red-800">{error}<button className="ml-3 underline" onClick={()=>setRefresh(r=>r+1)}>Riprova</button></div>}
  {notice&&<p role="status" className="rounded-xl bg-green-50 p-4 text-green-800">{notice}</p>}
  {loading?<p className={box}>Caricamento del conto…</p>:data&&<>
   <nav aria-label="Sezioni punti" className="flex gap-2 overflow-x-auto border-b border-pink-100 pb-3">{[['personal','I miei punti'],...(manageable.length?[['register','Registro eventi']]:[]),...(data.admin?[['summary','Riepilogo staff'],['settings','Gestione punti']]:[]),['rules','Regole e valori']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setNotice('')}} className={`whitespace-nowrap rounded-xl px-4 py-3 text-sm font-bold ${tab===id?'bg-pink-600 text-white':'bg-white text-neutral-600'}`}>{label}</button>)}</nav>
   {tab==='personal'&&p&&<>
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{p.name}</h2>{data.people.length>1&&<select className={input+' max-w-xs'} aria-label="Persona da consultare" value={p.id} onChange={e=>setSelected(e.target.value)}>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}</div>
    {!p.balance?<div className={box}><h3 className="font-bold">Livello da assegnare</h3><p className="mt-2 text-sm text-neutral-500">La direzione deve configurare il livello di questa persona per aprire il conto.</p>{data.admin&&<button className={button+' mt-4'} onClick={()=>setTab('settings')}>Configura in Gestione punti</button>}</div>:<>
     <section className="rounded-3xl border border-pink-200 bg-gradient-to-r from-pink-100 to-pink-50 p-7 text-neutral-900"><p className="text-xs uppercase tracking-widest text-pink-700">{BONUS_LEVELS[p.config!.level].label} · Conto del mese</p><div className="my-4 flex flex-wrap items-end justify-between gap-3"><strong className="text-5xl">{num(p.balance.points)} <span className="text-xl font-normal text-neutral-500">/ {p.balance.cap} pt</span></strong><strong className="text-3xl">{data.showValue&&p.balance.euros!==undefined?money(p.balance.euros):'Saldo in punti'}</strong></div><progress className="h-2 w-full accent-pink-600" value={p.balance.points} max={p.balance.cap}/></section>
     <div className="grid grid-cols-3 gap-3">{[['Base',p.balance.base],['Bonus',p.balance.bonus],['Malus',-p.balance.malus]].map(([label,n])=><div key={label} className={box}><p className="text-xs text-neutral-500">{label}</p><strong className="mt-2 block text-2xl">{num(Number(n))} pt</strong></div>)}</div>
     {p.config?.level!=='JUNIOR'&&<div className={box}><strong>Quota appuntamenti: {p.config?.quota??'da impostare'}</strong><p className="mt-2 text-xs text-neutral-500">Extra: +0,5 punti per appuntamento verificato oltre quota. Il collegamento automatico a Controllo Cliente è in preparazione; il registro richiede il totale verificato e il riferimento dell’appuntamento.</p></div>}
     <section className={box}><h3 className="mb-4 font-bold">Storico eventi · {p.account!.events.length}</h3>{!p.account!.events.length?<p className="text-sm text-neutral-500">Nessun evento. Il saldo parte dalla base del livello.</p>:[...p.account!.events].reverse().map(e=><article key={e.id} className="flex justify-between gap-4 border-t border-neutral-100 py-4"><div><strong className="text-sm">{BONUS_EVENT_LABELS[e.type]}</strong><p className="mt-1 text-xs text-neutral-500">{e.date.split('-').reverse().join('/')} · {e.actorName}</p><p className="mt-1 whitespace-pre-wrap text-xs text-neutral-500">{e.evidence}</p><p className="mt-1 text-xs">{e.reason}</p></div><strong className={e.points<0?'text-rose-600':'text-emerald-700'}>{e.points>0?'+':''}{num(e.points)} pt</strong></article>)}</section>
    </>}
   </>}
   {tab==='register'&&<EventForm key={`${month}-${data.revision}`} data={data} rows={manageable} onSave={()=>reload('Evento registrato nel database.')} />}
   {tab==='summary'&&data.admin&&<section className={box+' overflow-x-auto'}><h2 className="mb-4 text-xl font-bold">Riepilogo staff</h2><table className="w-full text-left text-sm"><thead><tr>{['Persona','Livello','Saldo','Valore'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.people.map(p=><tr key={p.id} className="border-t border-neutral-100"><td className="p-3"><button className="font-bold text-pink-700 underline" onClick={()=>{setSelected(p.id);setTab('personal')}}>{p.name}</button></td><td className="p-3">{p.config?BONUS_LEVELS[p.config.level].label:'Da assegnare'}</td><td className="p-3">{p.balance?`${num(p.balance.points)} / ${p.balance.cap}`:'—'}</td><td className="p-3">{p.balance?.euros!==undefined?money(p.balance.euros):'—'}</td></tr>)}</tbody></table></section>}
   {tab==='settings'&&data.admin&&<ConfigForm key={`${month}-${data.revision}-${selected}`} data={data} initialUser={selected} onSave={()=>reload('Configurazione salvata nel database.')} />}
   {tab==='rules'&&<section className={box}><h2 className="mb-4 text-xl font-bold">Bonus e malus</h2><ul className="space-y-3 text-sm">{['Ingresso: primi 3 ritardi senza malus, poi −10 punti ciascuno.','Pausa: primi 3 rientri tardi senza malus, poi −2 ciascuno.','Presentabilità: primi 2 richiami senza malus, poi −10 ciascuno.','Lettera di contestazione: −20 punti.','Rilavorazioni: prime 3 gratuite; −20 per blocco secondo la regola impostata dalla direzione.','Recensione negativa nominativa: −2 punti.','Recensione positiva nominativa: +1 dalla 21ª del mese.','Appuntamento extra: +0,5 oltre quota, solo Master e Autonome.','Cambio turno ultimo momento e reperibilità confermata: +1 ciascuno.','Junior: +2 per corso di formazione; +3 per zero rilavorazioni a mese concluso.','Puntualità: nessun bonus. Il saldo resta tra zero e il tetto e non si riporta al mese successivo.'].map(t=><li key={t}>{t}</li>)}</ul><div className="mt-6 grid gap-3 sm:grid-cols-3">{Object.values(BONUS_LEVELS).map(l=><div key={l.label} className="rounded-xl bg-pink-50 p-4"><strong>{l.label}</strong><p className="text-sm">Base {l.base} · Tetto {l.cap} pt</p></div>)}</div></section>}
  </>}
 </div>
}
function ConfigForm({data,initialUser,onSave}:{data:Data;initialUser:string;onSave:()=>void}){
 const [userId,setUserId]=useState(initialUser||data.people[0]?.id||''),[busy,setBusy]=useState(false),[error,setError]=useState('');const row=data.people.find(p=>p.id===userId),c=row?.config;
 return <section className={box}><h2 className="text-xl font-bold">Gestione punti</h2><div className="my-4 rounded-xl border border-pink-200 bg-pink-50 p-4"><strong>Valore economico allo staff: {data.valueVisible?'visibile':'nascosto'}</strong><p className="my-2 text-xs">La direzione vede sempre gli euro. Lo staff vede soltanto i punti finché non sblocchi questa opzione. L’impostazione vale per il mese selezionato e viene ripresa nei mesi successivi.</p><button type="button" disabled={busy} className={button} onClick={async()=>{setBusy(true);setError('');try{await post({action:'visibility',month:data.month,revision:data.revision,visible:!data.valueVisible});onSave()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{data.valueVisible?'Nascondi euro allo staff':'Sblocca euro per lo staff'}</button></div><p className="my-3 text-sm text-neutral-500">Configura il mese selezionato. Le assegnazioni vengono riprese nel mese successivo; lo storico dei mesi precedenti rimane separato.</p><label className="block text-sm">Persona<select className={input} disabled={busy} value={userId} onChange={e=>setUserId(e.target.value)}>{data.people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.locationName??'Sede non assegnata'}</option>)}</select></label>
 <form key={userId} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await post({action:'configure',month:data.month,revision:data.revision,config:{userId,level:f.get('level'),quota:f.get('quota')===''?null:Number(f.get('quota')),responsibleIds:f.getAll('responsible'),referenceMasterId:f.get('master')||null,reworkPolicy:f.get('policy')||null}});onSave()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><fieldset disabled={busy} className="mt-4 grid gap-4 sm:grid-cols-2">
  <label className="text-sm">Livello<select className={input} name="level" defaultValue={c?.level??''} required><option value="">Seleziona livello</option>{Object.entries(BONUS_LEVELS).map(([k,l])=><option key={k} value={k}>{l.label} · base {l.base}, tetto {l.cap}</option>)}</select></label>
  <label className="text-sm">Quota mensile appuntamenti<input className={input} name="quota" type="number" min="0" max="100000" step="1" defaultValue={c?.quota??''} placeholder="La imposti tu"/><span className="text-xs text-neutral-500">Vuota: bonus extra non disponibile. Solo Master e Autonome.</span></label>
  <label className="text-sm">Master di riferimento (Junior)<select name="master" className={input} defaultValue={c?.referenceMasterId??''}><option value="">Non assegnato</option>{data.people.filter(p=>p.id!==userId&&p.config?.level==='MASTER'&&!['ZERO','ADMIN','SUPER_ADMIN'].includes(p.role)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
  <label className="text-sm">Regola rilavorazioni<select className={input} name="policy" defaultValue={c?.reworkPolicy??''}><option value="">Da decidere</option><option value="COMPLETED_BLOCK">−20 alla 6ª, 9ª, 12ª</option><option value="STARTED_BLOCK">−20 alla 4ª, 7ª, 10ª</option></select></label>
  <div className="sm:col-span-2"><p className="mb-2 text-sm">Responsabili autorizzate a registrare</p>{data.assignments.filter(p=>p.role==='RESPONSABILE').map(p=><label key={p.id} className="mr-5 inline-flex gap-2 py-2 text-sm"><input type="checkbox" name="responsible" value={p.id} defaultChecked={c?.responsibleIds.includes(p.id)}/>{p.name}</label>)}</div>
  {error&&<p role="alert" className="text-red-700 sm:col-span-2">{error}</p>}<button className={button} type="submit">{busy?'Salvataggio…':'Salva configurazione'}</button>
 </fieldset></form><h3 className="mt-7 font-bold">Modifiche tracciate</h3>{data.audit.filter(a=>a.userId===userId).slice(-5).reverse().map(a=><p key={a.id} className="mt-2 text-xs text-neutral-500">{new Date(a.at).toLocaleString('it-IT')} · {a.actorName} · {a.after.level}, quota {a.after.quota??'non impostata'}</p>)}</section>
}
function EventForm({data,rows,onSave}:{data:Data;rows:Row[];onSave:()=>void}){
 const [userId,setUserId]=useState(rows[0]?.id??''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<{payload:Record<string,unknown>;points:number;reason:string}|null>(null);
 const row=rows.find(p=>p.id===userId);
 if(!row)return <p className={box}>Nessuna persona assegnata al tuo registro. La direzione può configurare le assegnazioni in Gestione punti.</p>;
 return <section className={box}><h2 className="text-xl font-bold">Registra un evento</h2><p className="my-3 text-sm text-neutral-500">Registrazione con riferimento verificato. I dati automatici di timbrature e clienti non sono ancora importati in questo conto.</p><form onChange={()=>setPreview(null)} onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{if(preview){await post({...preview.payload,action:'event'});onSave();return}const payload={action:'preview',month:data.month,userId,id:crypto.randomUUID(),type:f.get('type'),date:f.get('date'),evidence:f.get('evidence'),namedReviewConfirmed:f.get('named')==='on',zeroReworksConfirmed:f.get('zero')==='on',completedAppointments:f.get('appointments')===''?null:Number(f.get('appointments'))};const result=await post(payload);setPreview({payload:{...payload,revision:result.revision},points:result.preview.points,reason:result.preview.reason})}catch(e){setError((e as Error).message);setPreview(null)}finally{setBusy(false)}}}><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2">
 <label className="text-sm">Persona<select className={input} value={userId} onChange={e=>{setUserId(e.target.value);setPreview(null)}}>{rows.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label key={userId} className="text-sm">Voce<select className={input} name="type">{Object.entries(BONUS_EVENT_LABELS).filter(([t])=>canRegisterBonus(data.actor,row.config!,t as BonusEventType)).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
 <label className="text-sm">Data<input className={input} type="date" name="date" min={data.month===BONUS_START_MONTH?BONUS_START_DATE:data.month+'-01'} max={data.month===data.today.slice(0,7)?data.today:new Date(Number(data.month.slice(0,4)),Number(data.month.slice(5)),0,12).toISOString().slice(0,10)} defaultValue={data.month===data.today.slice(0,7)?data.today:data.month+'-28'} required/></label>
 <label className="text-sm">Totale appuntamenti verificati nel periodo<input name="appointments" className={input} type="number" min="0" step="1" placeholder="Solo per appuntamento extra"/></label>
 <label className="text-sm sm:col-span-2">Riferimento evento / appuntamento / corso<textarea className={input} name="evidence" maxLength={2000} required placeholder="Riferimento verificabile, non solo una descrizione generica"/></label>
 <label className="flex gap-2 text-sm"><input type="checkbox" name="named"/>Recensione: la cliente nomina esplicitamente questa persona.</label><label className="flex gap-2 text-sm"><input type="checkbox" name="zero"/>Zero rilavorazioni: ho verificato l’intero mese concluso.</label>
 {preview&&<div role="status" className="rounded-xl bg-pink-50 p-4 sm:col-span-2"><strong>{preview.points>0?'+':''}{num(preview.points)} pt · {data.showValue?money(preview.points*5):''}</strong><p className="mt-2 text-sm">{preview.reason}</p><p className="mt-2 text-xs">Confermando, l’evento entra nello storico con il tuo nome.</p></div>}
 {error&&<p role="alert" className="text-red-700 sm:col-span-2">{error}</p>}<button type="submit" className={button}>{busy?'Elaborazione…':preview?'Conferma registrazione':'Calcola anteprima'}</button>
 </fieldset></form></section>
}
