'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {emptyTeamNotes,PRESENTABILITY_REASONS,teamPending,type TeamNotes,type TeamPerson} from '@/lib/shift-team';
export type TeamSummary={total:number;pending:number};
type Report={people:TeamPerson[];notes:TeamNotes;version:string|null};
export function ShiftTeamPanel({day,onSummary}:{day:string;onSummary:(summary:TeamSummary|null)=>void}){
 const [report,setReport]=useState<Report|null>(null);const [notes,setNotes]=useState(emptyTeamNotes);const [dirty,setDirty]=useState(false);const dirtyRef=useRef(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const accept=useCallback((data:Report)=>{setReport(data);setNotes(data.notes);setDirty(false);dirtyRef.current=false;onSummary({total:data.people.length,pending:teamPending(data.people,data.notes)});},[onSummary]);
 const load=useCallback(async()=>{if(dirtyRef.current)return;try{const r=await fetch(`/api/shift-team?day=${day}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);accept(d);setError('');}catch(e){setError(e instanceof Error?e.message:'Errore caricamento');onSummary(null);}},[day,accept,onSummary]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),60000);return()=>clearInterval(timer);},[load]);
 function edit(value:TeamNotes){setNotes(value);setDirty(true);dirtyRef.current=true;setMessage('');}
 function decision(key:string,choice?:string,note?:string){const old=notes.decisions[key]||{choice:'',note:''};edit({...notes,decisions:{...notes.decisions,[key]:{choice:choice??old.choice,note:note??old.note}}});}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/shift-team',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({day,notes,version:report?.version})});const d=await r.json();if(!r.ok)throw new Error(d.error);accept(d);setMessage('Team salvato');}catch(e){setError(e instanceof Error?e.message:'Salvataggio non riuscito');}finally{setBusy(false);}}
 async function sickness(person:TeamPerson,key:string){setBusy(true);setError('');try{const r=await fetch('/api/shift-team',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({day,action:'sickness',userId:person.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);if(d.status!=='PENDING'&&d.status!=='APPROVED')throw new Error('La richiesta precedente è stata chiusa. Verifica nella pagina Richieste.');decision(key,'Malattia richiesta');setReport(old=>old?{...old,people:old.people.map(p=>p.id===person.id?{...p,sicknessPending:true}:p)}:old);setMessage('Richiesta di malattia registrata: deve essere approvata.');}catch(e){setError(e instanceof Error?e.message:'Richiesta non creata');}finally{setBusy(false);}}
 return <section className="shift-team-panel team-attendance-panel space-y-5 rounded-2xl border border-[#eadfe5] bg-white p-4 sm:p-5" aria-label="Controlli Team">
 <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-[#392936]">Presenze e pause</h2><p className="mt-1 text-sm text-neutral-600">Da timbrature e turnistica · compila solo giustificazioni ed eccezioni.</p></div><button type="button" className="team-button" disabled={busy||dirty} onClick={()=>void load()}>Aggiorna dati</button></header>
 {error&&<div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}{dirty&&<button type="button" className="team-button ml-2" onClick={()=>{dirtyRef.current=false;void load();}}>Scarta modifiche e ricarica</button>}</div>}
 {!report?<p>Caricamento timbrature…</p>:<>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="bg-[#f5f1f4] text-xs uppercase text-neutral-600">{['Persona','Turno','Entrata','Pausa','Uscita','Verifica della responsabile'].map(label=><th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{report.people.map(person=><tr key={person.id} data-attendance={person.inactive?'inactive':person.issues.length?'attention':'normal'} className={`border-b border-[#eee5eb] ${person.inactive?'bg-neutral-100 text-neutral-500':person.issues.length?'bg-[#fff3f8]':'bg-white'}`}>
 <th scope="row" className="p-3 font-semibold">{person.name}</th><td className="p-3">{person.shift}</td><td className="p-3" data-time-state={person.inactive?'inactive':person.issues.some(i=>i.type==='entry'||i.type==='missing')?'alert':person.entry!=='—'?'ontime':'neutral'}>{person.entry}</td><td className="p-3" data-time-state={person.inactive?'inactive':person.issues.some(i=>i.type==='pause')?'alert':'neutral'}>{person.pause}</td><td className="p-3">{person.exit}</td>
 <td className="min-w-64 p-3">{person.inactive?'Non in servizio':person.issues.length?person.issues.map(issue=><div key={issue.key} className="mb-3 last:mb-0"><p className="mb-2 font-semibold text-[#963b62]">{issue.label}</p>
 {issue.type==='missing'?<div className="flex flex-wrap gap-2"><button type="button" disabled={busy||person.sicknessPending} className="team-button" onClick={()=>void sickness(person,issue.key)}>{person.sicknessPending?'Malattia: richiesta in attesa':'Malattia (crea richiesta)'}</button>{['Assenza','Dimenticato di timbrare'].map(choice=><button type="button" disabled={busy} key={choice} className="team-button" aria-pressed={notes.decisions[issue.key]?.choice===choice} onClick={()=>decision(issue.key,choice)}>{choice}</button>)}</div>:issue.type!=='exit'&&<div className="flex flex-wrap gap-2">{['Giustificato','Non giustificato'].map(choice=><button type="button" disabled={busy} key={choice} className="team-button" aria-pressed={notes.decisions[issue.key]?.choice===choice} onClick={()=>decision(issue.key,choice)}>{choice}</button>)}</div>}
 <input disabled={busy} className="team-field mt-2" aria-label={`${issue.label} · nota per ${person.name}`} placeholder={issue.type==='exit'?'Motivo obbligatorio':'Nota facoltativa'} maxLength={5000} value={notes.decisions[issue.key]?.note||''} onChange={e=>decision(issue.key,undefined,e.target.value)}/></div>):'—'}</td></tr>)}</tbody></table></div>
 <section className="rounded-2xl border-2 border-[#c786a3] p-4"><h3 className="font-bold text-[#392936]">Presentabilità <span className="ml-2 text-xs font-normal text-[#963b62]">Solo eccezioni</span></h3><p className="my-2 text-sm text-neutral-600">Segnala solo chi non è in regola.</p>
 <button type="button" disabled={busy} className="team-button" aria-pressed={notes.presentation==='all'} onClick={()=>edit({...notes,presentation:'all',exceptions:[]})}>✓ Tutti in regola</button>
 {notes.presentation==='exceptions'&&notes.exceptions.map((exception,index)=><div key={index} className="mt-3 grid gap-2 rounded-xl bg-[#faeaf2] p-3 sm:grid-cols-2">
 <select className="team-field" disabled={busy} aria-label={`Persona eccezione ${index+1}`} value={exception.userId} onChange={e=>edit({...notes,exceptions:notes.exceptions.map((v,i)=>i===index?{...v,userId:e.target.value}:v)})}><option value="">Seleziona persona</option>{report.people.filter(p=>!p.inactive).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
 <select className="team-field" disabled={busy} aria-label={`Motivo eccezione ${index+1}`} value={exception.reason} onChange={e=>edit({...notes,exceptions:notes.exceptions.map((v,i)=>i===index?{...v,reason:e.target.value}:v)})}><option value="">Seleziona motivo</option>{PRESENTABILITY_REASONS.map(reason=><option key={reason}>{reason}</option>)}</select>
 <input className="team-field" disabled={busy} aria-label={`Nota eccezione ${index+1}`} placeholder="Nota sull’eccezione" maxLength={5000} value={exception.note} onChange={e=>edit({...notes,exceptions:notes.exceptions.map((v,i)=>i===index?{...v,note:e.target.value}:v)})}/><button type="button" disabled={busy} className="team-button" onClick={()=>edit({...notes,exceptions:notes.exceptions.filter((_,i)=>i!==index)})}>Rimuovi eccezione</button>
 </div>)}
 <button type="button" disabled={busy} className="team-button mt-3 block" onClick={()=>edit({...notes,presentation:'exceptions',exceptions:[...notes.exceptions,{userId:'',reason:'',note:''}]})}>+ Aggiungi eccezione</button></section>
 <footer className="flex flex-wrap items-center gap-3"><button type="button" disabled={busy||!dirty} className="team-button" data-primary="true" onClick={()=>void save()}>{busy?'Salvataggio…':'Salva Team'}</button><span role="status" className="text-sm text-emerald-800">{message|| (dirty?'Modifiche da salvare':'')}</span></footer>
 </>}
 </section>;
}
