"use client";
import { useState } from "react";
import type { MonthlyShiftReport } from "@/lib/shift-monthly-report";

type Props={initialMonth:string};
export function ShiftMonthlyReportPanel({initialMonth}:Props){
  const [month,setMonth]=useState(initialMonth),[report,setReport]=useState<MonthlyShiftReport|null>(null),[busy,setBusy]=useState(false),[pdfBusy,setPdfBusy]=useState(false),[error,setError]=useState("");
  async function load(){setBusy(true);setError("");setReport(null);try{const r=await fetch(`/api/shift-monthly-report?month=${encodeURIComponent(month)}`,{cache:"no-store"});const body=await r.json();if(!r.ok)throw new Error(body.error||"Impossibile caricare il report");setReport(body);}catch(e){setError(e instanceof Error?e.message:"Errore di caricamento");}finally{setBusy(false);}}
  async function download(){if(!report)return;setPdfBusy(true);setError("");try{const {monthlyShiftPdf}=await import("@/lib/shift-monthly-report-pdf");monthlyShiftPdf(report).save(`report-turni-clienti-${report.current.month}.pdf`);}catch{setError("Impossibile creare il PDF. Riprova.");}finally{setPdfBusy(false);}}
  const comparison=new Map<string,{name:string;salon:string;current:number;previous:number}>();
  if(report)for(const [key,rows]of [["current",report.clients.staff],["previous",report.previousClients.staff]] as const)for(const r of rows){const id=JSON.stringify([r.name,r.salon]);const row=comparison.get(id)||{name:r.name,salon:r.salon,current:0,previous:0};row[key]=r.services;comparison.set(id,row);}
  return <section className="rounded-[26px] border border-black/10 bg-white p-5 text-[#30212b] sm:p-7" aria-label="Report mensile responsabili e clienti">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h4 className="text-lg font-black">Report mensile: turni e clienti</h4><p className="mt-1 text-sm text-black/60">Confronta i verbali con le schede Controllo Cliente e scarica il PDF.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-xs font-bold">Mese<input type="month" value={month} min="2020-01" max={initialMonth} disabled={busy||pdfBusy} onChange={e=>{setMonth(e.target.value);setReport(null);setError("");}} className="mt-1 block rounded-xl border border-black/20 px-3 py-2" /></label><button type="button" disabled={!month||busy||pdfBusy} onClick={()=>void load()} className="min-h-11 rounded-xl bg-[#91305c] px-4 text-sm font-bold text-white disabled:opacity-40">{busy?"Caricamento...":"Analizza mese"}</button><button type="button" disabled={!report||busy||pdfBusy} onClick={()=>void download()} className="min-h-11 rounded-xl border border-black/20 px-4 text-sm font-bold disabled:opacity-40">{pdfBusy?"Creazione...":"Scarica PDF mensile"}</button></div></div>
    {error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}
    {report?<div className="mt-5 space-y-5"><p className="text-xs text-black/60">{report.current.firstDay} - {report.current.lastDay} confrontato con {report.previous.firstDay} - {report.previous.lastDay}. {report.current.partial?"Mese in corso: confronto fino allo stesso giorno, limitato alla durata del mese.":"Mesi completi."}</p>
      <div className="grid gap-3 sm:grid-cols-3">{[["Verbali compilati",report.shifts.days,report.previousShifts.days?`Precedente: ${report.previousShifts.days}`:"Precedente: dati non disponibili"],["Domande obbligatorie compilate",report.shifts.completion===null?"N/D":`${report.shifts.completion.toFixed(1)}%`,report.previousShifts.completion===null?"Precedente: dati non disponibili":`Precedente: ${report.previousShifts.completion.toFixed(1)}%`],["Schede cliente valide",report.clients.total,`Precedente: ${report.previousClients.total}`]].map(([label,value,note])=><div key={label} className="rounded-2xl bg-[#fcf1f6] p-4"><p className="text-xs font-bold">{label}</p><p className="my-1 text-3xl font-black">{value}</p><p className="text-xs text-black/60">{note}</p></div>)}</div>
      <p className="rounded-xl bg-amber-50 p-3 text-xs leading-relaxed">Le schede sono conteggiate per data di creazione; escluse “Errore” e “Finito”. Una scheda condivisa conta per ogni persona coinvolta, una sola volta nel totale salone. Non sono clienti unici. I verbali non hanno una sede associata e sono analizzati globalmente; la compilazione è ricalcolata sulle domande attuali.</p>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="pb-3 text-left font-bold">Schede cliente per collaboratrice / collaboratore</caption><thead><tr>{["Persona","Salone","Mese selezionato","Precedente","Differenza"].map(h=><th key={h} className="border-b p-2 text-xs">{h}</th>)}</tr></thead><tbody>{[...comparison.values()].sort((a,b)=>b.current-a.current||a.name.localeCompare(b.name)).map(r=><tr key={JSON.stringify([r.salon,r.name])}><td className="border-b p-2">{r.name}</td><td className="border-b p-2">{r.salon}</td><td className="border-b p-2 font-bold">{r.current}</td><td className="border-b p-2">{r.previous}</td><td className="border-b p-2">{r.current-r.previous>0?"+":""}{r.current-r.previous}</td></tr>)}</tbody></table>{!comparison.size?<p className="p-3 text-sm">Nessuna scheda nei due periodi.</p>:null}</div>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="pb-3 text-left font-bold">Risposte ai verbali</caption><thead><tr>{["Domanda","Risposte","Mancanti","Sì / No espliciti","Media voto"].map(h=><th key={h} className="border-b p-2 text-xs">{h}</th>)}</tr></thead><tbody>{report.shifts.questionStats.map(q=><tr key={q.id}><td className="border-b p-2">{q.title}</td><td className="border-b p-2">{q.answered}/{report.shifts.days}</td><td className="border-b p-2">{q.missing}</td><td className="border-b p-2">{q.yes} / {q.no}</td><td className="border-b p-2">{q.rating===null?"-":`${q.rating.toFixed(2)} (n=${q.ratingCount})`}</td></tr>)}</tbody></table></div><p className="text-xs text-black/60">Le risposte mancanti non sono esiti negativi. Nel PDF trovi anche checklist individuali e registro giornaliero. Nessuna classifica bonus automatica.</p>
    </div>:<p className="mt-4 text-sm text-black/50">Scegli il mese e premi “Analizza mese”.</p>}
  </section>;
}
