import {NextRequest,NextResponse} from 'next/server';
import {auth} from '@/lib/auth';
import {prisma} from '@/lib/prisma';
import {getCompleteCowlendarBookingsForRange} from '@/lib/cowlendar';
import {toShiftAppointmentClient} from '@/lib/shift-responsible-appointments';
import {romeDayRange} from '@/lib/shift-reports';
import {romeAgendaDate} from '@/lib/shift-agenda';
import {needsClientApproval,validClientCase,clientCaseFingerprint,type ClientCase} from '@/lib/shift-client-cases';
import {resolveShiftResponsible} from '@/lib/shift-responsible-selection-data';
import {emptyShiftAccessDay,hasShiftWriteAccess,normalizeShiftResponsibleAccess,SHIFT_RESPONSIBLE_ACCESS_KEY} from '@/lib/shift-responsible-access';
import {normalizeShiftResponsibleAssignments,WEEKLY_SHIFT_RESPONSIBLES_SETTING_KEY} from '@/lib/weekly-shift-responsibles';
const managers=new Set(['ZERO','SUPER_ADMIN','ADMIN']);const roles=new Set([...managers,'RESPONSABILE']);
const threshold=30;
async function load(day:string){const {start,end}=romeDayRange(day);const [bookings,staff,saved,performers]=await Promise.all([getCompleteCowlendarBookingsForRange(start.toISOString(),new Date(end.getTime()-1).toISOString()),prisma.user.findMany({where:{active:true,role:{in:['ZERO','SUPER_ADMIN','ADMIN','RESPONSABILE']}},select:{id:true,name:true},orderBy:{name:'asc'}}),prisma.setting.findUnique({where:{key:`shift_client_cases_${day}`}}),prisma.user.findMany({where:{active:true,location:{name:{contains:"Buenos Aires",mode:"insensitive"}}},select:{id:true,name:true},orderBy:{name:"asc"}})]);return {clients:bookings.flatMap(b=>{const c=toShiftAppointmentClient(b);return c?[c]:[];}),staff,performers,threshold,...(saved?.value as {cases:ClientCase[];version:string}|null||{cases:[],version:null})};}
export async function GET(request:NextRequest){const session=await auth();if(!session?.user?.id||!roles.has(session.user.role))return NextResponse.json({error:'Non autorizzato'},{status:403});const day=request.nextUrl.searchParams.get('day');if(!day||!/^\d{4}-\d{2}-\d{2}$/.test(day)||day>romeAgendaDate(new Date())||(!managers.has(session.user.role)&&day!==romeAgendaDate(new Date())))return NextResponse.json({error:'Giorno non valido'},{status:400});try{return NextResponse.json({...await load(day),canApprove:managers.has(session.user.role)},{headers:{'Cache-Control':'private, no-store'}});}catch{return NextResponse.json({error:'Casi e appuntamenti non disponibili.'},{status:502});}}
export async function PUT(request:NextRequest){
 const session=await auth();if(!session?.user?.id||!roles.has(session.user.role))return NextResponse.json({error:'Non autorizzato'},{status:403});const body=await request.json().catch(()=>null);if(!body?.day||!/^\d{4}-\d{2}-\d{2}$/.test(body.day)||body.day>romeAgendaDate(new Date())||((body.action!=='decide'||!managers.has(session.user.role))&&body.day!==romeAgendaDate(new Date())))return NextResponse.json({error:'Giorno non valido'},{status:400});
 if(body.action==='decide'){if(!managers.has(session.user.role)||!['APPROVED','DENIED'].includes(body.decision))return NextResponse.json({error:'Solo la direzione può autorizzare.'},{status:403});}
 else {const [access,assignment]=await Promise.all([prisma.setting.findUnique({where:{key:SHIFT_RESPONSIBLE_ACCESS_KEY}}),prisma.setting.findUnique({where:{key:WEEKLY_SHIFT_RESPONSIBLES_SETTING_KEY}})]);if(!hasShiftWriteAccess(normalizeShiftResponsibleAccess(access?.value)[body.day]||emptyShiftAccessDay(),session.user.id,await resolveShiftResponsible(body.day,normalizeShiftResponsibleAssignments(assignment?.value)[body.day])))return NextResponse.json({error:'Serve la presa visione e il permesso di compilare.'},{status:403});}
 try{const data=await load(body.day);const key=`shift_client_cases_${body.day}`;const setting=await prisma.setting.findUnique({where:{key}});const current=setting?.value as {cases:ClientCase[];version:string}|null;if((current?.version||null)!==body.version)return NextResponse.json({error:'Casi aggiornati nel frattempo. Ricarica.'},{status:409});let cases:ClientCase[];
 if(body.action==='decide'){const target=current?.cases.find(c=>c.id===body.id);if(!target||target.status!=='PENDING')return NextResponse.json({error:'Richiesta non in attesa.'},{status:409});cases=current!.cases.map(c=>c.id===body.id?{...c,status:body.decision,approvedBy:session.user.name||session.user.id,approvedAt:new Date().toISOString()}:c);}
 else {if(!Array.isArray(body.cases)||body.cases.length>100||new Set(body.cases.map((c:ClientCase)=>c?.id)).size!==body.cases.length||!body.cases.every((c:ClientCase)=>validClientCase(c,new Set(data.clients.map(b=>b.id)),new Set(data.staff.map(p=>p.id)),new Set(data.performers.map(p=>p.id)))))return NextResponse.json({error:'Completa cliente, chi ha svolto il servizio, problema, soluzione ed esito. Per soluzioni con costo indica importo e chi ha autorizzato.'},{status:400});
 if(current?.cases.some(old=>!body.cases.some((c:ClientCase)=>c.id===old.id)))return NextResponse.json({error:'I casi già salvati devono rimanere nel verbale.'},{status:400});
 cases=body.cases.map((c:ClientCase)=>{const old=current?.cases.find(o=>o.id===c.id);const approval=needsClientApproval(c,threshold);const same=old&&clientCaseFingerprint(old)===clientCaseFingerprint(c);return {id:c.id,bookingId:c.bookingId,description:c.description.trim(),performedBy:c.performedBy,solution:c.solution,amount:c.solution==='Nessun costo'?'0':c.amount,authorizedBy:c.authorizedBy,resolved:c.resolved,status:approval?(same?old.status:'PENDING'):'RECORDED',...(same&&old.approvedBy?{approvedBy:old.approvedBy,approvedAt:old.approvedAt}:{})};});}
 const value=JSON.parse(JSON.stringify({cases,version:new Date().toISOString(),savedBy:session.user.id}));
 await prisma.$transaction(async tx=>{
 if(setting){const result=await tx.setting.updateMany({where:{key,value:{equals:setting.value!}},data:{value}});if(!result.count)throw new Error('CONFLICT');}else await tx.setting.create({data:{key,value}});
 const pending=cases.filter(c=>c.status==='PENDING'&&(!current?.cases.some(old=>old.id===c.id&&old.status==='PENDING'&&clientCaseFingerprint(old)===clientCaseFingerprint(c))));
 if(pending.length){const recipients=await tx.user.findMany({where:{active:true,OR:[{role:{in:['ZERO','SUPER_ADMIN','ADMIN']}},{role:'RESPONSABILE',id:{in:pending.map(c=>c.authorizedBy).filter(Boolean)}}]},select:{id:true,role:true}});await tx.notification.createMany({data:recipients.map(user=>({user_id:user.id,title:'Casi clienti da autorizzare',message:`${pending.length} richieste di autorizzazione nel verbale del ${body.day}.`,type:'TURNO',action_url:managers.has(user.role)?`/client-case-approvals?day=${body.day}`:'/responsabile-di-turno'}))});}
 });
 return NextResponse.json({...await load(body.day),canApprove:managers.has(session.user.role)});
 }catch{return NextResponse.json({error:'Salvataggio non riuscito. Riprova.'},{status:500});}
}
