ALTER TABLE "staff_tasks"
ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'Operativa',
ADD COLUMN IF NOT EXISTS "checklist" JSONB,
ADD COLUMN IF NOT EXISTS "attachment_name" TEXT,
ADD COLUMN IF NOT EXISTS "attachment_url" TEXT,
ADD COLUMN IF NOT EXISTS "photo_url" TEXT,
ADD COLUMN IF NOT EXISTS "link_url" TEXT,
ADD COLUMN IF NOT EXISTS "notes" TEXT;
