ALTER TABLE "branding_settings"
ADD COLUMN IF NOT EXISTS "dark_background_color" TEXT NOT NULL DEFAULT '#121114',
ADD COLUMN IF NOT EXISTS "dark_sidebar_color" TEXT NOT NULL DEFAULT '#1B1A1F',
ADD COLUMN IF NOT EXISTS "dark_card_color" TEXT NOT NULL DEFAULT '#201F24',
ADD COLUMN IF NOT EXISTS "dark_text_color" TEXT NOT NULL DEFAULT '#F8F3F6',
ADD COLUMN IF NOT EXISTS "dark_button_color" TEXT NOT NULL DEFAULT '#F4A3C4';
